{% set name = "celery" %}
{% set version = "5.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/celery-{{ version }}.tar.gz
  sha256: 870cc71d737c0200c397290d730344cc991d13a057534353d124c9380267aab9

build:
  number: 0
  noarch: python
  entry_points:
    - celery = celery.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
  run:
    - billiard >=4.2.0,<5.0
    - click >=8.1.2,<9.0
    - click-didyoumean >=0.3.0
    - click-plugins >=1.1.1
    - click-repl >=0.2.0
    - kombu >=5.3.2,<6.0
    - importlib-metadata >=3.6
    - backports.zoneinfo >=0.2.1
    - python >=3.7
    - python-tzdata >=2022.7
    - python-dateutil >=2.8.2
    - pytz >=2021.3
    - vine >=5.1.0,<6.0

test:
  requires:
    - dnspython
    - pymongo
    - pytest
    - pytest-celery
    - pytest-subtests
    - pytest-timeout
    - pytest-click
    - boto3>=1.9.178
    - moto>=2.2.6
    - pip
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.app.task
    - celery.apps
    - celery.backends
    # Requires sqlalchemy but it's an optional dependency
    # - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - pip check
    - celery --version
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - efiop
    - chrisburr
    - kwilcox
    - sodre
