{% set name = "celery" %}
{% set version = "5.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/celery-{{ version }}.tar.gz
  sha256: 8d9a3de9162965e97f8e8cc584c67aad83b3f7a267584fa47701ed11c3e0d4b0

build:
  number: 2
  noarch: python
  entry_points:
    - celery = celery.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - billiard >=3.6.4.0,<4.0
    - click >=8.0,<9.0
    - click-didyoumean >=0.0.3
    - click-plugins >=1.1.1
    - click-repl >=0.2.0
    - cryptography
    - kombu >=5.1.0,<6.0
    - python >=3.6
    - pytz
    - setuptools
    - vine >=5.0.0,<6.0
  run_constrained:
    - sphinx >=2.0

test:
  requires:
    - boto3 >=1.9.178
    - case >=1.3.1
    - moto
    - pytest 6.2.*
    - pytest-celery
    - pytest-timeout 1.4.2.*
    - pytest-subtests
    - pip
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.app.task
    - celery.apps
    - celery.backends
    # Requires sqlalchemy but it's an optional dependency
    # - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - pip check
    - celery --version
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - chrisburr
    - kwilcox
    - pmlandwehr
    - sodre
    - igortg
    - mcs07
    - hadim
