{% set name = "celery" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 65f061c04578cf189cd7352c192e1a79fdeb370b916bff792bcc769560e81184

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - celery = celery.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytz
    - billiard >=3.6.3,<4.0
    - kombu >=5.0.0,<6.0
    - vine >=5.0.0,<6.0
    - sqlalchemy
    - click >=7.0
    - click-didyoumean >=0.0.3
    - click-repl >=0.1.6
    - click-plugins >=1.1.1
    - cryptography
  run_constrained:
    - sphinx >=2.0

test:
  requires:
    - boto3 >=1.9.178
    - case >=1.3.1
    - moto ==1.3.7
    - pytest 6.2.*
    - pytest-celery
    - pytest-timeout 1.4.2.*
    - pytest-subtests
    - pip
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.app.task
    - celery.apps
    - celery.backends
    - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - pip check
    - celery --version
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - kwilcox
    - pmlandwehr
    - sodre
    - igortg
    - mcs07
