{% set name = "celery" %}
{% set version = "5.2.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/celery-{{ version }}.tar.gz
  sha256: fafbd82934d30f8a004f81e8f7a062e31413a23d444be8ee3326553915958c6d

build:
  number: 0
  noarch: python
  entry_points:
    - celery = celery.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.7
  run:
    - billiard >=3.6.4.0,<4.0
    - click >=8.0.3,<9.0
    - click-didyoumean >=0.0.3
    - click-plugins >=1.1.1
    - click-repl >=0.2.0
    - kombu >=5.2.3,<6.0
    - importlib-metadata >=1.4.0
    - python >=3.7
    - pytz >=2021.3
    - vine >=5.0.0,<6.0

test:
  requires:
    - dnspython
    - pymongo
    - pytest~=6.2
    - pytest-celery
    - pytest-subtests
    - pytest-timeout~=1.4.2
    - boto3>=1.9.178
    - moto>=2.2.6
    - pip
  source_files:
    - t
  imports:
    - celery
    - celery.app
    - celery.app.task
    - celery.apps
    - celery.backends
    # Requires sqlalchemy but it's an optional dependency
    # - celery.backends.database
    - celery.bin
    - celery.concurrency
    - celery.contrib
    - celery.events
    - celery.fixups
    - celery.loaders
    - celery.security
    - celery.utils
    - celery.utils.dispatch
    - celery.worker
  commands:
    - pip check
    - celery --version
    - celery worker --help
    - celery beat --help
    - celery multi help
    - celery shell --help
    - pytest t/unit

about:
  home: http://celeryproject.org
  license_file: LICENSE
  license: BSD-3-Clause
  summary: Distributed Task Queue
  dev_url: https://github.com/celery/celery
  doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
  recipe-maintainers:
    - efiop
    - chrisburr
    - kwilcox
    - sodre
    - igortg
    - mcs07
