{% set name = "celery" %}
{% set version = "4.2.0" %}
{% set sha256 = "77ff3730198d6a17b3c1f05579ebe570b579efb35f6d7e13dba3b1368d068b35" %}
{% set build = 0 %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: {{ build }}
    script: python setup.py install --single-version-externally-managed --record=record.txt
    entry_points:
        - celery = celery.__main__:main

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pytz
        - billiard >=3.5.0.2,<3.6
        - kombu >=4.0.2,<5.0
        - sqlalchemy

test:
    requires:
        - case >=1.3.1
        - pytest >=3.0
    source_files:
        - t
    imports:
        - celery
        - celery.app
        - celery.apps
        - celery.backends
        - celery.backends.database
        - celery.bin
        - celery.concurrency
        - celery.contrib
        - celery.events
        - celery.fixups
        - celery.loaders
        - celery.security
        - celery.task
        - celery.utils
        - celery.utils.dispatch
        - celery.worker

    commands:
        - celery --version
        - celery worker --help
        - celery beat --help
        - celery multi help
        - celery shell --help
        - pytest t/unit  # [py3k]

about:
    home: http://celeryproject.org
    license_file: LICENSE
    license: BSD 3-Clause
    summary: Distributed Task Queue
    dev_url: https://github.com/celery/celery
    doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
    recipe-maintainers:
        - kwilcox
        - pmlandwehr
        - sodre
